### PR TITLE
Get all PAS derived plots working

### PR DESCRIPTION
**Pull request by danbek**
Matt,

More PAS plots. Still some cosmetic fixes to make, but it's improving. Will send an email with more questions.

Dan

### CODE REVIEW

**Comment by mtat76** [comment]
It appears that we have a memory leak and this thing is a complete CPU hog (I was pumping at something near 50% on the PAS page).  When not on the PAS page, my memory utilization was stable and the CPU usage was negligible suggesting we have an issue with the NVD3 implementation.
Styling will be absolutely necessary as the current implementation is totally off - there are too many digits being displayed obscuring the visualization and the last plot is not aligned with the rest; are they all in the same container?

**The absolute most important thing though is that we get the performance to reasonable level!!!!**  If we can't, we have major problems.

**Comment by danbek** [comment]
Styling should be easy.

I wonder how one goes about profiling a web page? I wonder how much of this
is a problem with nvd3 vs d3 itself, vs something that we might be doing.

Dan

On Sun, Jun 14, 2015 at 11:52 PM, Matt Richardson <notifications@github.com>
wrote:

> It appears that we have a memory leak and this thing is a complete CPU hog
> (I was pumping at something near 50% on the PAS page). When not on the PAS
> page, my memory utilization was stable and the CPU usage was negligible
> suggesting we have an issue with the NVD3 implementation.
> Styling will be absolutely necessary as the current implementation is
> totally off - there are too many digits being displayed obscuring the
> visualization and the last plot is not aligned with the rest; are they all
> in the same container?
>
> *The absolute most important thing though is that we get the performance
> to reasonable level!!!!* If we can't, we have major problems.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mtat76/exscalabar/pull/9#issuecomment-111934309>.
>



-- 
Dan Becker

**Comment by danbek** [comment]
That was easy:

https://developer.chrome.com/devtools/docs/cpu-profiling

https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Profiling_with_the_Built-in_Profiler

I'll look at this, might have to wait till tomorrow night.

Dan

On Mon, Jun 15, 2015 at 3:15 PM, Dan Becker <db19606@gmail.com> wrote:

> Styling should be easy.
>
> I wonder how one goes about profiling a web page? I wonder how much of
> this is a problem with nvd3 vs d3 itself, vs something that we might be
> doing.
>
> Dan
>
> On Sun, Jun 14, 2015 at 11:52 PM, Matt Richardson <
> notifications@github.com> wrote:
>
>> It appears that we have a memory leak and this thing is a complete CPU
>> hog (I was pumping at something near 50% on the PAS page). When not on the
>> PAS page, my memory utilization was stable and the CPU usage was negligible
>> suggesting we have an issue with the NVD3 implementation.
>> Styling will be absolutely necessary as the current implementation is
>> totally off - there are too many digits being displayed obscuring the
>> visualization and the last plot is not aligned with the rest; are they all
>> in the same container?
>>
>> *The absolute most important thing though is that we get the performance
>> to reasonable level!!!!* If we can't, we have major problems.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mtat76/exscalabar/pull/9#issuecomment-111934309>.
>>
>
>
>
> --
> Dan Becker
>



-- 
Dan Becker

**Comment by mtat76** [comment]
OK.  Another thing that I noticed is that the controller code was located outside of the IIFE.  We will probably need to place this in the IIFE.  

Also, I noticed that the html is calling for more columns for each plot.  If we want to show multiple plots on a page, the best way to do it would be to declare them in a single column and then have multiple rows.  This should fix the alignment issue. 

I am going to work at reducing the number of plots using an angular directive called [context-menu](https://github.com/Templarian/ui.bootstrap.contextMenu).  That way we don't have a bunch of different plots in the space running at the same time.  Maybe this will limit the cpu issues?  Anyways, I am going to commit and submit a pull request.

**Comment by mtat76** [comment]
Also, when you are operating on an array in javascript, you may want to consider using map.  I believe that this is faster.

**Pull request merged**
