### PR TITLE
revisiting flot

### PR DESCRIPTION
**Pull request by danbek**
Hi Matt,

The question about why nvd3 instead of flot made me think, especially since I had already been wondering whether we could improve performance by using an html canvas instead of svg.

So I just hacked up the PAS plots using flot. It's in a branch called try-flot in my repo, not sure how this will come over to your repo.

The PAS page is still UGLY ... I did not attempt to add labels, make the plots centered properly, etc. But it allows us to do a basic performance comparison. Code is not exactly ideal either. But anyway ...

On windows 8.1 firefox, the CPU is still high, but it feel more responsive. Memory usage keeps increasing until it has acquired 300 seconds of data, and then levels off (though I only let it go 10-15 minutes).

On windows 8.1 chrome, cpu usable is MUCH lower ... not even breaking a sweat. It's somewhat ridiculous.

Seems like we switch to flot, tell them to use chrome if they want it to run smooth? We'll have to write some extra js to support choosing the cells that you want to plot, but they provide an example of that (http://www.flotcharts.org/flot/examples/series-toggle/index.html)

The following link seems to indicate that flot should play nicely with bootstrap, but I've not got it to work yet:

http://www.bootply.com/5M8erlHV65

### CODE REVIEW

**Comment by mtat76** [comment]
Were you seeing some issues with NVD3?  I still am not certain whether we are getting memory issues with NVD3 yet.  The CPU issues don't bother me as much as some crashing that I saw.  flot seems simpler, so it wouldn't be surprising to me that it would work more robustly.

For integrating flot with angular, check here:

http://stackoverflow.com/questions/13103671/how-to-integrate-flot-with-angularjs

I am not going to pull it quite yet, but feel free to keep working on it.  I am ok with moving back to flot if you think it is better.

**Comment by danbek** [comment]
Yes, that SO answer is what I followed when getting this to work.

I thought that you were very concerned about performance, and CPU usage in
particular? If that's not the case we could stick with nvd3. But if
performance is a concern at all (and given that you want to update the
plots every second), it really looks like flot is better choice.

I think you can create a branch and pull my changes into that branch if you
want to just try it out.

Dan

Dan

On Sun, Jun 21, 2015 at 11:54 PM, Matt Richardson <notifications@github.com>
wrote:

> Were you seeing some issues with NVD3? I still am not certain whether we
> are getting memory issues with NVD3 yet. The CPU issues don't bother me as
> much as some crashing that I saw. flot seems simpler, so it wouldn't be
> surprising to me that it would work more robustly.
>
> For integrating flot with angular, check here:
>
>
> http://stackoverflow.com/questions/13103671/how-to-integrate-flot-with-angularjs
>
> I am not going to pull it quite yet, but feel free to keep working on it.
> I am ok with moving back to flot if you think it is better.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mtat76/exscalabar/pull/11#issuecomment-114013063>.
>



-- 
Dan Becker

**Comment by mtat76** [comment]
I wonder if we have missed something with NVD3, though.  The reason I asked about your experience is I wanted to make sure it wasn't just me.  The biggest problem seems to be on the page with multiple plots.  I am going to take a closer look at this to see if it might be the angular-nvd3 implementation.

**Comment by danbek** [comment]
Got it. My experience is also that nvd3 chews CPU on both firefox and
chrome, while flot chews cpu on firefox (but somewhat less than nvd3) but
works great on chrome. So it's definitely not just you!

If you look at the changes I made to get flot working, I changed as little
as possible - still using all the angular infrastructure for broadcasting
data changes. One change is that I'm using a single controller for all the
plots, instead of separate controllers for each plot.

I think the main things I liked about nvd3 vs flot were (1) it was easy to
dynamically change the interval of data that you are viewing in nvd3 (2)
nvd3 has built-in support to let you choose which data series to plot. But
we aren't even doing (1) anymore, and we can get something like (2) working
easily (though it won't be as pretty as for nvd3).

Dan

On Mon, Jun 22, 2015 at 11:02 AM, Matt Richardson <notifications@github.com>
wrote:

> I wonder if we have missed something with NVD3, though. The reason I asked
> about your experience is I wanted to make sure it wasn't just me. The
> biggest problem seems to be on the page with multiple plots. I am going to
> take a closer look at this to see if it might be the angular-nvd3
> implementation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mtat76/exscalabar/pull/11#issuecomment-114179455>.
>



-- 
Dan Becker

**Comment by danbek** [comment]
Having problems with flot. Doesn't support toggling plots on/off
out-of-the-box ... there is a plugin, but having a devil of a time getting
it to work. Also the axis labels are not working well, and also not playing
nicely with bootstrap.

I may look at canvas.js, it seems to support all this nicely out of box:

http://canvasjs.com/docs/charts/how-to/hide-unhide-data-series-chart-legend-click/

Dan

On Mon, Jun 22, 2015 at 12:39 PM, Matt Richardson <notifications@github.com>
wrote:

> Merged #11 <https://github.com/mtat76/exscalabar/pull/11>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mtat76/exscalabar/pull/11#event-337017700>.
>



-- 
Dan Becker

**Comment by mtat76** [comment]
Dan,

We can make flot work.  If canvas is going to require significant time to understand and get to do what we want, lets stick with flot for now.  [We can toggle things off and on with flot](http://www.flotcharts.org/flot/examples/series-toggle/index.html), so this would work and we can make it prettier if necessary.  *If* you can get canvas running quickly, go for it.

Matt

**Pull request merged**
